//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Questioning {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Resource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Questioning.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &gt;.
        /// </summary>
        public static string Cmd_PromptInputCommand {
            get {
                return ResourceManager.GetString("Cmd_PromptInputCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на :.
        /// </summary>
        public static string Cmd_PromptInputData {
            get {
                return ResourceManager.GetString("Cmd_PromptInputData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на delete.
        /// </summary>
        public static string CmdDelete {
            get {
                return ResourceManager.GetString("CmdDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на delete &quot;&lt;Фамилия Имя Отчество&gt;&quot;.
        /// </summary>
        public static string CmdDelete_Format {
            get {
                return ResourceManager.GetString("CmdDelete_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить указанную анкету.
        /// </summary>
        public static string CmdDelete_Help {
            get {
                return ResourceManager.GetString("CmdDelete_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на exit.
        /// </summary>
        public static string CmdExit {
            get {
                return ResourceManager.GetString("CmdExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выйти из приложения.
        /// </summary>
        public static string CmdExit_Help {
            get {
                return ResourceManager.GetString("CmdExit_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на find.
        /// </summary>
        public static string CmdFind {
            get {
                return ResourceManager.GetString("CmdFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на find &quot;&lt;Фамилия Имя Отчество&gt;&quot;.
        /// </summary>
        public static string CmdFind_Format {
            get {
                return ResourceManager.GetString("CmdFind_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Найти анкету и показать данные анкеты в консоль.
        /// </summary>
        public static string CmdFind_Help {
            get {
                return ResourceManager.GetString("CmdFind_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на goto_prev_question.
        /// </summary>
        public static string CmdGotoPrevQuestion {
            get {
                return ResourceManager.GetString("CmdGotoPrevQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вернуться к предыдущему вопросу (Команда доступна только при заполнении анкеты, вводится вместо ответа на любой вопрос).
        /// </summary>
        public static string CmdGotoPrevQuestion_Help {
            get {
                return ResourceManager.GetString("CmdGotoPrevQuestion_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на goto_question.
        /// </summary>
        public static string CmdGotoQuestion {
            get {
                return ResourceManager.GetString("CmdGotoQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на goto_question &lt;номер вопроса&gt;.
        /// </summary>
        public static string CmdGotoQuestion_Format {
            get {
                return ResourceManager.GetString("CmdGotoQuestion_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вернуться к указанному вопросу (Команда доступна только при заполнении анкеты, вводится вместо ответа на любой вопрос).
        /// </summary>
        public static string CmdGotoQuestion_Help {
            get {
                return ResourceManager.GetString("CmdGotoQuestion_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на help.
        /// </summary>
        public static string CmdHelp {
            get {
                return ResourceManager.GetString("CmdHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Показать список доступных команд с описанием.
        /// </summary>
        public static string CmdHelp_Help {
            get {
                return ResourceManager.GetString("CmdHelp_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на list.
        /// </summary>
        public static string CmdList {
            get {
                return ResourceManager.GetString("CmdList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Показать список названий файлов всех сохранённых анкет.
        /// </summary>
        public static string CmdList_Help {
            get {
                return ResourceManager.GetString("CmdList_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на list_today.
        /// </summary>
        public static string CmdListToday {
            get {
                return ResourceManager.GetString("CmdListToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Показать список названий файлов всех сохранённых анкет, созданных сегодня.
        /// </summary>
        public static string CmdListToday_Help {
            get {
                return ResourceManager.GetString("CmdListToday_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на new_profile.
        /// </summary>
        public static string CmdNewProfile {
            get {
                return ResourceManager.GetString("CmdNewProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заполнить новую анкету.
        /// </summary>
        public static string CmdNewProfile_Help {
            get {
                return ResourceManager.GetString("CmdNewProfile_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на restart_profile.
        /// </summary>
        public static string CmdRestartProfile {
            get {
                return ResourceManager.GetString("CmdRestartProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заполнить анкету заново (Команда доступна только при заполнении анкеты, вводится вместо ответа на любой вопрос).
        /// </summary>
        public static string CmdRestartProfile_Help {
            get {
                return ResourceManager.GetString("CmdRestartProfile_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на save.
        /// </summary>
        public static string CmdSave {
            get {
                return ResourceManager.GetString("CmdSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить заполненную анкету.
        /// </summary>
        public static string CmdSave_Help {
            get {
                return ResourceManager.GetString("CmdSave_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на statistics.
        /// </summary>
        public static string CmdStatistics {
            get {
                return ResourceManager.GetString("CmdStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Показать статистику всех заполненных анкет.
        /// </summary>
        public static string CmdStatistics_Help {
            get {
                return ResourceManager.GetString("CmdStatistics_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на zip.
        /// </summary>
        public static string CmdZip {
            get {
                return ResourceManager.GetString("CmdZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на zip &quot;&lt;Фамилия Имя Отчество&gt;&quot; &lt;путь&gt;.
        /// </summary>
        public static string CmdZip_Format {
            get {
                return ResourceManager.GetString("CmdZip_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запаковать указанную анкету в архив и сохранить архив по указанному пути.
        /// </summary>
        public static string CmdZip_Help {
            get {
                return ResourceManager.GetString("CmdZip_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Средний возраст.
        /// </summary>
        public static string Label_AverageAge {
            get {
                return ResourceManager.GetString("Label_AverageAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата рождения.
        /// </summary>
        public static string Label_DR {
            get {
                return ResourceManager.GetString("Label_DR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Опыт программирования на указанном языке.
        /// </summary>
        public static string Label_ExperienceProgrammingInspecifiedLanguage {
            get {
                return ResourceManager.GetString("Label_ExperienceProgrammingInspecifiedLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Любимый язык программирования.
        /// </summary>
        public static string Label_FavoriteProgramLanguage {
            get {
                return ResourceManager.GetString("Label_FavoriteProgramLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ФИО.
        /// </summary>
        public static string Label_FIO {
            get {
                return ResourceManager.GetString("Label_FIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мобильный телефон.
        /// </summary>
        public static string Label_MobilePhone {
            get {
                return ResourceManager.GetString("Label_MobilePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Анкета заполнена.
        /// </summary>
        public static string Label_ProfileFilledOudDate {
            get {
                return ResourceManager.GetString("Label_ProfileFilledOudDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Самый популярный язык программирования.
        /// </summary>
        public static string Label_TopProgramLanguage {
            get {
                return ResourceManager.GetString("Label_TopProgramLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата рождения не может быть больше текущей даты.
        /// </summary>
        public static string Test_DRCanNotBeMoreCurrentDate {
            get {
                return ResourceManager.GetString("Test_DRCanNotBeMoreCurrentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Опыт не может быть больше возраста.
        /// </summary>
        public static string Test_ExperienceCanNotBeMoreAge {
            get {
                return ResourceManager.GetString("Test_ExperienceCanNotBeMoreAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Путь для сохранения архива.
        /// </summary>
        public static string Text_ArchivePath {
            get {
                return ResourceManager.GetString("Text_ArchivePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Команда может использоваться только при заполнении данных анкеты.
        /// </summary>
        public static string Text_CommandContextError {
            get {
                return ResourceManager.GetString("Text_CommandContextError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка при выполнении команды.
        /// </summary>
        public static string Text_CommandError {
            get {
                return ResourceManager.GetString("Text_CommandError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка.
        /// </summary>
        public static string Text_CommandParserError {
            get {
                return ResourceManager.GetString("Text_CommandParserError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка ввода данных.
        /// </summary>
        public static string Text_DataError {
            get {
                return ResourceManager.GetString("Text_DataError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Формат ДД.ММ.ГГГГ.
        /// </summary>
        public static string Text_DateFormat {
            get {
                return ResourceManager.GetString("Text_DateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ответ не должно быть пустым.
        /// </summary>
        public static string Text_EmptyConstraintMsg {
            get {
                return ResourceManager.GetString("Text_EmptyConstraintMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Полных лет.
        /// </summary>
        public static string Text_FullYear {
            get {
                return ResourceManager.GetString("Text_FullYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Язык можно выбрать только из: {0}.
        /// </summary>
        public static string Text_LanguageMastBeIn {
            get {
                return ResourceManager.GetString("Text_LanguageMastBeIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Длина ответа ({0}) не должна превышать {1} символов.
        /// </summary>
        public static string Text_LengthMaxConstraintMsg {
            get {
                return ResourceManager.GetString("Text_LengthMaxConstraintMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Длина ответа ({0}) не должна быть меньше {1} символов.
        /// </summary>
        public static string Text_LengthMinConstraintMsg {
            get {
                return ResourceManager.GetString("Text_LengthMinConstraintMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Требуется обязательный параметр.
        /// </summary>
        public static string Text_NeedRequeryParameter {
            get {
                return ResourceManager.GetString("Text_NeedRequeryParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Номер вопроса.
        /// </summary>
        public static string Text_NumberQuestion {
            get {
                return ResourceManager.GetString("Text_NumberQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Номер вопроса должен быть числом.
        /// </summary>
        public static string Text_NumberQuestionMustBeNumber {
            get {
                return ResourceManager.GetString("Text_NumberQuestionMustBeNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Номер вопроса должен быть положительным числом от 1 до {0}.
        /// </summary>
        public static string Text_NumberQuestionMustBePositiveNumber {
            get {
                return ResourceManager.GetString("Text_NumberQuestionMustBePositiveNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите не пустое значение.
        /// </summary>
        public static string Text_ParserEmptyValue {
            get {
                return ResourceManager.GetString("Text_ParserEmptyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка при разборе пользовательского ввода.
        /// </summary>
        public static string Text_ParserOtherError {
            get {
                return ResourceManager.GetString("Text_ParserOtherError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не известная команда.
        /// </summary>
        public static string Text_ParserUnknownCommand {
            get {
                return ResourceManager.GetString("Text_ParserUnknownCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя файла анкеты.
        /// </summary>
        public static string Text_Questionary {
            get {
                return ResourceManager.GetString("Text_Questionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите действие.
        /// </summary>
        public static string Text_SelectAction {
            get {
                return ResourceManager.GetString("Text_SelectAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не верный формат ответа.
        /// </summary>
        public static string Text_WrongFormatAnswer {
            get {
                return ResourceManager.GetString("Text_WrongFormatAnswer", resourceCulture);
            }
        }
    }
}
